project:
  type: website
  output-dir: _site
  resources: 
    - "*.csv"

website:
  title: "Personal and Research Data Management: Organize, Clean & Enrich"
  description: "Workshop materials for doctoral students - UPPA & CHORAL"
  favicon: img/favicon.png
  repo-url: "https://github.com/ujubib/tdh-data"
  repo-actions: [source, issue]
  navbar:
    right:
      - icon: git
        href: https://github.com/ujubib/tdh-data
      - icon: envelope
        href: mailto:julien.rabaud@univ-pau.fr

  sidebar:
    style: "floating"
    background: FloralWhite
    contents:
      - section: "Workshop"
        contents:
          - text: "Home"
            href: index.qmd
          - text: "Slides"
            href: slides.qmd
      - section: "Additional Resources"
        contents:
          - text: "File Organization Tools"
            href: resources/archifiltre.qmd
          - text: "File Naming & Backup"
            href: resources/file-management.qmd
          - text: "OpenRefine Tutorials"
            href: resources/openrefine.qmd

  page-footer:
    background: FloralWhite
    border: false
    right: "Last update: {{< meta site-date >}}"

site-date: 2026-02-09

format:
  html:
    theme: [journal, custom.scss]
    css: styles.css
    backgroundcolor: FloralWhite
    lang: en
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    reference-location: margin
    number-sections: false
